install:
    - npm install -g typescript
    - npm install -g jasmine

build_script: 
    - ps: | 
        mkdir -force .\out > $null
        tsc .\gototab\popup.ts

test_script:
    - jasmine

on_finish:
    - ps: |
        Compress-Archive .\gototab -DestinationPath .\out\gototab.zip
        ls .\out | % { Push-AppveyorArtifact $_.FullName }
